<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Bivariate Data Analysis | Fundamentals of Data Analysis in R</title>
  <meta name="description" content="<p>This is a collection of tutorials that illustrate how to analyse data in R.
The topics touched on this collection span univariate data analysis, multivariate data analysis, and fundamentals of machine learning.</p>" />
  <meta name="generator" content="bookdown 0.28.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Bivariate Data Analysis | Fundamentals of Data Analysis in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a collection of tutorials that illustrate how to analyse data in R.
The topics touched on this collection span univariate data analysis, multivariate data analysis, and fundamentals of machine learning.</p>" />
  <meta name="github-repo" content="eddiecg/Data-analysis-in-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Bivariate Data Analysis | Fundamentals of Data Analysis in R" />
  
  <meta name="twitter:description" content="<p>This is a collection of tutorials that illustrate how to analyse data in R.
The topics touched on this collection span univariate data analysis, multivariate data analysis, and fundamentals of machine learning.</p>" />
  

<meta name="author" content="Eddie Cano-Gamez" />


<meta name="date" content="2022-08-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="univariate-data-analysis.html"/>
<link rel="next" href="multivariate-data-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Fundamentals of Data Analysis in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to Programming in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#calculations-in-r"><i class="fa fa-check"></i><b>1.1</b> Calculations in R</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#variable-assignation-in-r"><i class="fa fa-check"></i><b>1.2</b> Variable assignation in R</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#data-types-in-r"><i class="fa fa-check"></i><b>1.3</b> Data types in R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#numeric-variables"><i class="fa fa-check"></i><b>1.3.1</b> Numeric variables</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#character-variables"><i class="fa fa-check"></i><b>1.3.2</b> Character variables</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#logical-variables"><i class="fa fa-check"></i><b>1.3.3</b> Logical variables</a></li>
<li class="chapter" data-level="1.3.4" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#categorical-variables-factors"><i class="fa fa-check"></i><b>1.3.4</b> Categorical variables (factors)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#working-with-multiple-numbers-in-r"><i class="fa fa-check"></i><b>1.4</b> Working with multiple numbers in R</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#vectors"><i class="fa fa-check"></i><b>1.4.1</b> Vectors</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#lists"><i class="fa fa-check"></i><b>1.4.2</b> Lists</a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#matrices"><i class="fa fa-check"></i><b>1.4.3</b> Matrices</a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#data-frames"><i class="fa fa-check"></i><b>1.4.4</b> Data frames</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#manipulating-data-in-r"><i class="fa fa-check"></i><b>1.5</b> Manipulating data in R</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#working-with-lists-of-data-frames"><i class="fa fa-check"></i><b>1.5.1</b> Working with lists of data frames</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#extending-rs-funcitonality-with-libraries"><i class="fa fa-check"></i><b>1.6</b> Extending R’s funcitonality with libraries</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#writing-data-from-r"><i class="fa fa-check"></i><b>1.7</b> Writing data from R</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#writing-human-readable-files"><i class="fa fa-check"></i><b>1.7.1</b> Writing human readable files</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#writing-binary-files"><i class="fa fa-check"></i><b>1.7.2</b> Writing binary files</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#reading-data-into-r"><i class="fa fa-check"></i><b>1.8</b> Reading data into R</a></li>
<li class="chapter" data-level="1.9" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#project-work"><i class="fa fa-check"></i><b>1.9</b> Project work</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html"><i class="fa fa-check"></i><b>2</b> Univariate Data Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#visualising-univariate-data"><i class="fa fa-check"></i><b>2.1</b> Visualising univariate data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#dot-plot-strip-chart"><i class="fa fa-check"></i><b>2.1.1</b> Dot plot / Strip chart</a></li>
<li class="chapter" data-level="2.1.2" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#histograms"><i class="fa fa-check"></i><b>2.1.2</b> Histograms</a></li>
<li class="chapter" data-level="2.1.3" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#density-plot"><i class="fa fa-check"></i><b>2.1.3</b> Density plot</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#summarising-univariate-data"><i class="fa fa-check"></i><b>2.2</b> Summarising univariate data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#mean"><i class="fa fa-check"></i><b>2.2.1</b> Mean</a></li>
<li class="chapter" data-level="2.2.2" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#median"><i class="fa fa-check"></i><b>2.2.2</b> Median</a></li>
<li class="chapter" data-level="2.2.3" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#quantiles"><i class="fa fa-check"></i><b>2.2.3</b> Quantiles</a></li>
<li class="chapter" data-level="2.2.4" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#standard-deviation"><i class="fa fa-check"></i><b>2.2.4</b> Standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#comparing-data-to-probability-distributions"><i class="fa fa-check"></i><b>2.3</b> Comparing data to probability distributions</a></li>
<li class="chapter" data-level="2.4" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#box-plots"><i class="fa fa-check"></i><b>2.4</b> Box plots</a></li>
<li class="chapter" data-level="2.5" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#data-as-a-random-sample"><i class="fa fa-check"></i><b>2.5</b> Data as a random sample</a></li>
<li class="chapter" data-level="2.6" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
<li class="chapter" data-level="2.7" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#references"><i class="fa fa-check"></i><b>2.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html"><i class="fa fa-check"></i><b>3</b> Bivariate Data Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#visualising-two-variables"><i class="fa fa-check"></i><b>3.1</b> Visualising two variables</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#scatter-plot"><i class="fa fa-check"></i><b>3.1.1</b> Scatter plot</a></li>
<li class="chapter" data-level="3.1.2" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#bivariate-box-plots"><i class="fa fa-check"></i><b>3.1.2</b> Bivariate box plots</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#applying-transformations-to-a-variable"><i class="fa fa-check"></i><b>3.2</b> Applying transformations to a variable</a></li>
<li class="chapter" data-level="3.3" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#using-ggplot2-to-create-personalised-plots"><i class="fa fa-check"></i><b>3.3</b> Using ggplot2 to create personalised plots</a></li>
<li class="chapter" data-level="3.4" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#exercises-1"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
<li class="chapter" data-level="3.5" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#covariance"><i class="fa fa-check"></i><b>3.5</b> Covariance</a></li>
<li class="chapter" data-level="3.6" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#correlation"><i class="fa fa-check"></i><b>3.6</b> Correlation</a></li>
<li class="chapter" data-level="3.7" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#predictions-and-linear-models"><i class="fa fa-check"></i><b>3.7</b> Predictions and linear models</a></li>
<li class="chapter" data-level="3.8" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#correlation-does-not-equal-causation"><i class="fa fa-check"></i><b>3.8</b> Correlation does not equal causation</a></li>
<li class="chapter" data-level="3.9" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#exercises-2"><i class="fa fa-check"></i><b>3.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html"><i class="fa fa-check"></i><b>4</b> Multivariate Data Analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#exploring-one-variable-at-a-time"><i class="fa fa-check"></i><b>4.1</b> Exploring one variable at a time</a></li>
<li class="chapter" data-level="4.2" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#analysing-all-variables-jointly"><i class="fa fa-check"></i><b>4.2</b> Analysing all variables jointly</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#scatter-plot-matrices"><i class="fa fa-check"></i><b>4.2.1</b> Scatter plot matrices</a></li>
<li class="chapter" data-level="4.2.2" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#correlation-plots"><i class="fa fa-check"></i><b>4.2.2</b> Correlation plots</a></li>
<li class="chapter" data-level="4.2.3" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#the-distance-matrix"><i class="fa fa-check"></i><b>4.2.3</b> The distance matrix</a></li>
<li class="chapter" data-level="4.2.4" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#clustering-and-dendrograms"><i class="fa fa-check"></i><b>4.2.4</b> Clustering and dendrograms</a></li>
<li class="chapter" data-level="4.2.5" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#heatmaps"><i class="fa fa-check"></i><b>4.2.5</b> Heatmaps</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#exercises-3"><i class="fa fa-check"></i><b>4.3</b> Exercises</a></li>
<li class="chapter" data-level="4.4" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#reducing-the-number-of-dimensions"><i class="fa fa-check"></i><b>4.4</b> Reducing the number of dimensions</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#combining-dimensionality-reduction-with-clustering"><i class="fa fa-check"></i><b>4.4.1</b> Combining dimensionality reduction with clustering</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#exercises-4"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
<li class="chapter" data-level="4.6" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#references-1"><i class="fa fa-check"></i><b>4.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html"><i class="fa fa-check"></i><b>5</b> Web scraping in R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#example-scraping-the-imdb-website"><i class="fa fa-check"></i><b>5.1</b> Example: Scraping the IMDB website</a></li>
<li class="chapter" data-level="5.2" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#extracting-variables-using-css-selectors"><i class="fa fa-check"></i><b>5.2</b> Extracting variables using CSS selectors</a></li>
<li class="chapter" data-level="5.3" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#scraping-multiple-fields-from-a-website"><i class="fa fa-check"></i><b>5.3</b> Scraping multiple fields from a website</a></li>
<li class="chapter" data-level="5.4" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#performing-exploratory-data-analysis-eda-on-scraped-data"><i class="fa fa-check"></i><b>5.4</b> Performing exploratory data analysis (EDA) on scraped data</a></li>
<li class="chapter" data-level="5.5" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#exercises-5"><i class="fa fa-check"></i><b>5.5</b> Exercises</a></li>
<li class="chapter" data-level="5.6" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#references-2"><i class="fa fa-check"></i><b>5.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><i class="fa fa-check"></i><b>6</b> Machine Learning Fundamentals: Spam Detection Using a Naive Bayes Classifier</a>
<ul>
<li class="chapter" data-level="6.1" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#visualising-data"><i class="fa fa-check"></i><b>6.1</b> Visualising data</a></li>
<li class="chapter" data-level="6.2" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#pre-processing-data"><i class="fa fa-check"></i><b>6.2</b> Pre-processing data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#converting-data-to-corpus"><i class="fa fa-check"></i><b>6.2.1</b> Converting data to corpus</a></li>
<li class="chapter" data-level="6.2.2" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#cleaning-data"><i class="fa fa-check"></i><b>6.2.2</b> Cleaning data</a></li>
<li class="chapter" data-level="6.2.3" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#visualising-clean-data"><i class="fa fa-check"></i><b>6.2.3</b> Visualising clean data</a></li>
<li class="chapter" data-level="6.2.4" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#tokenising"><i class="fa fa-check"></i><b>6.2.4</b> Tokenising</a></li>
<li class="chapter" data-level="6.2.5" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#dividing-data-into-training-and-testing-set"><i class="fa fa-check"></i><b>6.2.5</b> Dividing data into training and testing set</a></li>
<li class="chapter" data-level="6.2.6" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#correcting-data-sparsity"><i class="fa fa-check"></i><b>6.2.6</b> Correcting data sparsity</a></li>
<li class="chapter" data-level="6.2.7" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#converting-data-to-word-appearance-table"><i class="fa fa-check"></i><b>6.2.7</b> Converting data to word appearance table</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#predicting-spam-and-non-spam"><i class="fa fa-check"></i><b>6.3</b> Predicting spam and non-spam</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#training-classifier"><i class="fa fa-check"></i><b>6.3.1</b> Training classifier</a></li>
<li class="chapter" data-level="6.3.2" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#testing-classifier"><i class="fa fa-check"></i><b>6.3.2</b> Testing classifier</a></li>
<li class="chapter" data-level="6.3.3" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#evaluating-performance"><i class="fa fa-check"></i><b>6.3.3</b> Evaluating performance</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#discussion"><i class="fa fa-check"></i><b>6.4</b> Discussion</a></li>
<li class="chapter" data-level="6.5" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#references-3"><i class="fa fa-check"></i><b>6.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><i class="fa fa-check"></i><b>7</b> Machine Learning Fundamentals: Predicting Variables Using Neural Networks</a>
<ul>
<li class="chapter" data-level="7.1" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#normalising-data"><i class="fa fa-check"></i><b>7.1</b> Normalising data</a></li>
<li class="chapter" data-level="7.2" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#visualising-data-1"><i class="fa fa-check"></i><b>7.2</b> Visualising data</a></li>
<li class="chapter" data-level="7.3" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#creating-neural-network"><i class="fa fa-check"></i><b>7.3</b> Creating neural network</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#spliting-data-into-training-and-testing-sets"><i class="fa fa-check"></i><b>7.3.1</b> Spliting data into training and testing sets</a></li>
<li class="chapter" data-level="7.3.2" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#training-neural-network"><i class="fa fa-check"></i><b>7.3.2</b> Training neural network</a></li>
<li class="chapter" data-level="7.3.3" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#testing-neural-network"><i class="fa fa-check"></i><b>7.3.3</b> Testing neural network</a></li>
<li class="chapter" data-level="7.3.4" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#evaluating-performance-1"><i class="fa fa-check"></i><b>7.3.4</b> Evaluating performance</a></li>
<li class="chapter" data-level="7.3.5" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#improving-performance-by-adding-hidden-nodes"><i class="fa fa-check"></i><b>7.3.5</b> Improving performance by adding hidden nodes</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#conclusions"><i class="fa fa-check"></i><b>7.4</b> Conclusions</a></li>
<li class="chapter" data-level="7.5" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#references-4"><i class="fa fa-check"></i><b>7.5</b> References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fundamentals of Data Analysis in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bivariate-data-analysis" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Bivariate Data Analysis<a href="bivariate-data-analysis.html#bivariate-data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>During the previous session we learned how to analyse data with a single variable. Most of the times, however, big data will not contain one but multiple variables (hence its size!). To move forward in this direction, let’s now learn how to analyse datasets which contain two variables. We call this type of data bivariate.</p>
<p>Before starting this session you will need to install the packages “MVA”, “dslabs” and “ggplot”. You can do that by running the following lines:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="bivariate-data-analysis.html#cb264-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;MVA&quot;</span>)</span>
<span id="cb264-2"><a href="bivariate-data-analysis.html#cb264-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;dslabs&quot;</span>)</span>
<span id="cb264-3"><a href="bivariate-data-analysis.html#cb264-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb264-4"><a href="bivariate-data-analysis.html#cb264-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;ggrepel&quot;</span>)</span></code></pre></div>
<p>Now that the installation has completed, let’s load them.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="bivariate-data-analysis.html#cb265-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HSAUR2)</span>
<span id="cb265-2"><a href="bivariate-data-analysis.html#cb265-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MVA)</span>
<span id="cb265-3"><a href="bivariate-data-analysis.html#cb265-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span>
<span id="cb265-4"><a href="bivariate-data-analysis.html#cb265-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb265-5"><a href="bivariate-data-analysis.html#cb265-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb265-6"><a href="bivariate-data-analysis.html#cb265-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rafalib)</span></code></pre></div>
<p>Now we are ready to start.</p>
<p>Loading the package “dslabs” will add a number of datasets to your R session. One of them is “murders”, which contains FBI records for murders by gun in several US states. These records were collected in 2010. Let’s assign this data set to a variable called “dat” (dat for data).</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="bivariate-data-analysis.html#cb266-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> murders</span></code></pre></div>
<p>Let’s look at the first few lines of the data set.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="bivariate-data-analysis.html#cb267-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code></pre></div>
<pre><code>##        state abb region population total
## 1    Alabama  AL  South    4779736   135
## 2     Alaska  AK   West     710231    19
## 3    Arizona  AZ   West    6392017   232
## 4   Arkansas  AR  South    2915918    93
## 5 California  CA   West   37253956  1257
## 6   Colorado  CO   West    5029196    65</code></pre>
<p>Notice that the data contains four variables: Name of US state, abreviation of the state, region to which it belongs, size of the population for that state and total number of murders by gun registered. Of these variables, we will focus on the two numeric ones: population size and number of gun murders. Throughout this session we will try to ask a very simple question:</p>
<p>Are this two variables related? Or, in other words, are there more murders by gun in places where the population is bigger?</p>
<div id="visualising-two-variables" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Visualising two variables<a href="bivariate-data-analysis.html#visualising-two-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Eery one of these two variables (poulation size and number of murders) can be analysed using the techniques we learnt about in the previous session. For example, we can create a histogram of population size, and find out how populated states tend to be:</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="bivariate-data-analysis.html#cb269-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dat<span class="sc">$</span>total, <span class="at">breaks=</span><span class="dv">10</span>, <span class="at">main=</span><span class="st">&quot;&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Population&quot;</span>, <span class="at">freq=</span>F, <span class="at">col=</span><span class="st">&quot;grey&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-153-1.png" width="672" /></p>
<p>We can explore the number of murders in the exact same way:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="bivariate-data-analysis.html#cb270-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dat<span class="sc">$</span>total, <span class="at">breaks=</span><span class="dv">10</span>, <span class="at">main=</span><span class="st">&quot;&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Population&quot;</span>, <span class="at">freq=</span>F, <span class="at">col=</span><span class="st">&quot;grey&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-154-1.png" width="672" /></p>
<p>This already tells us that US states are highly variable both in terms of population and number of murders. In other words, while some states (like California) have more than 30 million inhabitants, some others (as Wyoming) hace only half a million.</p>
<p>However, we are analysing the variables in isolation. In other words, we are analysing them separately instead of together (jointly). Let’s now learn about some methods to visualise them at the same time, perhaps this can inform us of any relationship between them.</p>
<div id="scatter-plot" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Scatter plot<a href="bivariate-data-analysis.html#scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A scatter plot is a plot of two variables in which each variable is encoded in each of the axes (X axis and Y axis). Pairs of valus are represented by points with an X and a Y coordinate. It is by far the most used plot in the entire field of statistics (and perhaps in a lot of sciences). Let’s create a plot with population size in the X axis and number of murders on the Y. To do this, we use the function “plot()”. The first value is the x and the second value the y.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="bivariate-data-analysis.html#cb271-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>population, dat<span class="sc">$</span>total, <span class="at">xlab=</span><span class="st">&quot;Population size&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Number of gun murders&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-155-1.png" width="672" /></p>
<p>If we want to preserve the information we got from the historgrams for each variable and on top of that plot them together, we can add “marginal” distributions. They are called marginal because they literally are drawn on the “margins” or axes. You can think of them as tiny stripcharts/dot plots. To add marginal stripcharts in R, use the function rug().</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="bivariate-data-analysis.html#cb272-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>population, dat<span class="sc">$</span>total, <span class="at">xlab=</span><span class="st">&quot;Population size&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Number of gun murders&quot;</span>)</span>
<span id="cb272-2"><a href="bivariate-data-analysis.html#cb272-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(dat<span class="sc">$</span>population, <span class="at">side=</span><span class="dv">1</span>)</span>
<span id="cb272-3"><a href="bivariate-data-analysis.html#cb272-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(dat<span class="sc">$</span>total, <span class="at">side=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-156-1.png" width="672" /></p>
</div>
<div id="bivariate-box-plots" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Bivariate box plots<a href="bivariate-data-analysis.html#bivariate-box-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we want to know where the majority of our data is, we can use an “extension” of hte box plot in 2 dimensions (we learnt about the box plot in the previous session). This extension is called “bivariate box plot” (because it displays two variables) and we can draw it in R using the function “bvbox()”.</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="bivariate-data-analysis.html#cb273-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bvbox</span>(dat[,<span class="fu">c</span>(<span class="st">&quot;population&quot;</span>,<span class="st">&quot;total&quot;</span>)],<span class="at">xlab =</span> <span class="st">&quot;Population in millions&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Number of murders&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-157-1.png" width="672" /></p>
<p>We can read this plot is as follows: there is a central ellipse which is the equivalent to the box of a boxplot, the central 50% of the data will be inside it. Surrounding it, there is a bigger ellipse (dotted lines), this is the equivalent of the “whiskers” of the boxplot and most of the data (ideally all) should fall inside it. The potential outliers can are dots falling outside the ellipses.</p>
<p>In this case, we can see 4 states with unusually high population and number of murders. These points are outisde the ellipses, so perhaps they are outliers.</p>
</div>
</div>
<div id="applying-transformations-to-a-variable" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Applying transformations to a variable<a href="bivariate-data-analysis.html#applying-transformations-to-a-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>But are those points in the precious plots really outliers? There is a slight problem with this: we saw before that our data is quite variable and spread. Some states have tens of millions of inhabitants and some others fewer than a million. It is difficult to compare states when they are so different!</p>
<p>If you are still not convinced, look at the following density plot:</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="bivariate-data-analysis.html#cb274-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(dat<span class="sc">$</span>population), <span class="at">main=</span><span class="st">&quot;&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Population size&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-158-1.png" width="672" /></p>
<p>Do you see the long “tail” towards the left side of the plot? It is made of states with unusually high population size.</p>
<p>In cases like this, when the numbers vary so much and can be tiny or massive, we sometimes need to “transform” the data. What this means is that we modify it in a way that makes it more compressed, comparable and easy to handle.</p>
<p>One of the most common ways of “transforming” data is applying a logarithm. If you have studeid any logarithms before, you’ll remember that they are the opposite operation to exponents. Logarithms are very useful because they can be used to transform differences of hundreds or thousands into differences of units. For example, let’s look at the following series of numbers:</p>
<p>1, 10, 100, 1000, 100000, 1000000</p>
<p>They increase very fast! However, if we apply a simple logarithm (base 10) to them, the series becomes:</p>
<p>1, 2, 3, 4, 5, 6</p>
<p>Which is much easier to see and analyse.</p>
<p>Let’s apply a logarithm to the population size:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="bivariate-data-analysis.html#cb275-1" aria-hidden="true" tabindex="-1"></a>logpopulation <span class="ot">&lt;-</span> <span class="fu">log10</span>(dat<span class="sc">$</span>population<span class="sc">+</span><span class="dv">1</span>)</span></code></pre></div>
<p>Note we had to add 1 before applying the logarithm. This is because log(0) equals infinity, and R cannot deal with inifinte numbers (and neither can we).</p>
<p>Now let’s create a density plot of the “log-population size”:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="bivariate-data-analysis.html#cb276-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(logpopulation), <span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;log10(Population size)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-160-1.png" width="672" /></p>
<p>Compare this density plot with the previous one. Now the tail has dissapeared and our data looks like the usual “bell shape” we found in the previous session! The numbers on the x axis on this plot (5, 6, 7, 8) would be equivalent to 100000, 1000000, 10000000, 100000000 in the linear scale.</p>
<p>Let’s apply the logarithm to the number of murders too and plot it “against” the population size (against here means in the same plot). Let’s also add marginal stripcharts</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="bivariate-data-analysis.html#cb277-1" aria-hidden="true" tabindex="-1"></a>logmurders <span class="ot">&lt;-</span> <span class="fu">log10</span>(dat<span class="sc">$</span>total <span class="sc">+</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="bivariate-data-analysis.html#cb278-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(logpopulation,logmurders,<span class="at">xlab =</span> <span class="st">&quot;log10( Population in millions )&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;log10( Number of murders )&quot;</span>)</span>
<span id="cb278-2"><a href="bivariate-data-analysis.html#cb278-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(logpopulation, <span class="at">side=</span><span class="dv">1</span>)</span>
<span id="cb278-3"><a href="bivariate-data-analysis.html#cb278-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(logmurders, <span class="at">side=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-162-1.png" width="672" /></p>
<p>Now the plot looks much better! We can actually see all the points and they are evenly spaced. In fact, now it starts becoming obvious that there is some relationship between population size and number of gun murders. When one increses, the other increases too. They form some sort of straight line.</p>
<p>Since the logarithms worked so well, let’s replace the original variables in our data with their transformations:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="bivariate-data-analysis.html#cb279-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>population <span class="ot">&lt;-</span> logpopulation</span>
<span id="cb279-2"><a href="bivariate-data-analysis.html#cb279-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>total <span class="ot">&lt;-</span> logmurders</span></code></pre></div>
<p>Let’s create a bivariate box plot now using the “transformed” (log) data.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="bivariate-data-analysis.html#cb280-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bvbox</span>(dat[,<span class="fu">c</span>(<span class="st">&quot;population&quot;</span>,<span class="st">&quot;total&quot;</span>)],</span>
<span id="cb280-2"><a href="bivariate-data-analysis.html#cb280-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">&quot;log( Population in millions )&quot;</span>,</span>
<span id="cb280-3"><a href="bivariate-data-analysis.html#cb280-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab=</span><span class="st">&quot;log( Number of murders )&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-164-1.png" width="672" /></p>
<p>Notice how all the outliers have dissapeared. They were not really outliers, they were just too populated states compared with the rest and the comaprison was unfair.</p>
</div>
<div id="using-ggplot2-to-create-personalised-plots" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Using ggplot2 to create personalised plots<a href="bivariate-data-analysis.html#using-ggplot2-to-create-personalised-plots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far we have been using the functions plot(), hist(), density(), etc… However, there if we want to make very specific changes to our plot (like making our favorite point a different colour or changing the background) it becomes difficult. There is a better way to draw plots in R which allows us to modify every single aspect of the plot: it is done using the package ggplot.</p>
<p>The ggplot package is big and learning how to use it takes time. We will not focus on this during this course, but let’s have a quick look at the things we can do with it.</p>
<p>Let’s start by creating the same scatter plot we have above, but using ggplot: we use the funciton ggplot() and specify where our data is stored, next we use “aes()” and include inside the parenthesis the things we want R to use as X and Y variables, in this case the population and the number of murders.</p>
<p>Then we add (+) an indication of the type of plot we want. In this case, we want a scatter plot where each value is a point, so we use “geom_point()” (which stands for geomtry of points).</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="bivariate-data-analysis.html#cb281-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb281-2"><a href="bivariate-data-analysis.html#cb281-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb281-3"><a href="bivariate-data-analysis.html#cb281-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb281-4"><a href="bivariate-data-analysis.html#cb281-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-165-1.png" width="672" /></p>
<p>This looks nice, but the grey background is ugly. Let’s remove the grey! To do that, we simply add (+) another indication telling R to use a “white background (bw)”. You’ll start to notice how ggplot works: you use the + symbol to add more and more indications and specifications and make your plot personalised to what you really want.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="bivariate-data-analysis.html#cb282-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb282-2"><a href="bivariate-data-analysis.html#cb282-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb282-3"><a href="bivariate-data-analysis.html#cb282-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb282-4"><a href="bivariate-data-analysis.html#cb282-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>) <span class="sc">+</span></span>
<span id="cb282-5"><a href="bivariate-data-analysis.html#cb282-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-166-1.png" width="672" /></p>
<p>Let’s now change the colout of the points to blue. To do this, we add a color indication (color=“blue”) inside geom_point():</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="bivariate-data-analysis.html#cb283-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb283-2"><a href="bivariate-data-analysis.html#cb283-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb283-3"><a href="bivariate-data-analysis.html#cb283-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb283-4"><a href="bivariate-data-analysis.html#cb283-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>) <span class="sc">+</span></span>
<span id="cb283-5"><a href="bivariate-data-analysis.html#cb283-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-167-1.png" width="672" /></p>
<p>But ggplot can do more than colouring points blue! In fact, we can use the colour not only as a visual decoration, but to actually represent something. For example, let’s tell R to color the points by region (each color will represent a US region). Notice how, whenever we refer to a variable inside our data set, we have to use aes().</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="bivariate-data-analysis.html#cb284-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb284-2"><a href="bivariate-data-analysis.html#cb284-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>region)) <span class="sc">+</span> </span>
<span id="cb284-3"><a href="bivariate-data-analysis.html#cb284-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb284-4"><a href="bivariate-data-analysis.html#cb284-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>) <span class="sc">+</span></span>
<span id="cb284-5"><a href="bivariate-data-analysis.html#cb284-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-168-1.png" width="672" /></p>
<p>Now we can in fact read not only 2 but 2 variables in the same plots! This plot actually has three dimensions, one of which is the color. Have a go, can you find any particular region with higher population than the rest?</p>
<p>If you have difficulty distinguishing colors, that is no problem. Instead of coding by color we can ask R to code by “shape”, so that each region is represented by a different figure (triangle, square, cross, etc…). It now looks like this:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="bivariate-data-analysis.html#cb285-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb285-2"><a href="bivariate-data-analysis.html#cb285-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">shape=</span>region), <span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb285-3"><a href="bivariate-data-analysis.html#cb285-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb285-4"><a href="bivariate-data-analysis.html#cb285-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>) <span class="sc">+</span></span>
<span id="cb285-5"><a href="bivariate-data-analysis.html#cb285-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-169-1.png" width="672" /></p>
<p>We can even add a fourth variable to our plot! For example, let’s add labels with the abbreviated name of each state. In that way we will not only get their population and number of murders: we will also know which specific state we are talking about.</p>
<p>To do this, we add yet another indication (+) called geom_text() and specify that we wan the label to be “abb”” the state abbreviation included in our data set.</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="bivariate-data-analysis.html#cb286-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb286-2"><a href="bivariate-data-analysis.html#cb286-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>region)) <span class="sc">+</span> </span>
<span id="cb286-3"><a href="bivariate-data-analysis.html#cb286-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb286-4"><a href="bivariate-data-analysis.html#cb286-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>) <span class="sc">+</span></span>
<span id="cb286-5"><a href="bivariate-data-analysis.html#cb286-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>abb)) <span class="sc">+</span> </span>
<span id="cb286-6"><a href="bivariate-data-analysis.html#cb286-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-170-1.png" width="672" /></p>
<p>This is nice, however the labels no longer let us see the actual points or colours: they get on the way. To avoid this, instead of using geom_text we can use geom_text_repel, which tells R not to let the text crash with the points or with other text. Let’s see how it looks like now.</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="bivariate-data-analysis.html#cb287-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb287-2"><a href="bivariate-data-analysis.html#cb287-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>region)) <span class="sc">+</span> </span>
<span id="cb287-3"><a href="bivariate-data-analysis.html#cb287-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb287-4"><a href="bivariate-data-analysis.html#cb287-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>) <span class="sc">+</span></span>
<span id="cb287-5"><a href="bivariate-data-analysis.html#cb287-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label=</span>abb)) <span class="sc">+</span> </span>
<span id="cb287-6"><a href="bivariate-data-analysis.html#cb287-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-171-1.png" width="672" /></p>
<p>Much better and cleaner! Now we are ready to continue with more formal comparisons that rely not only on our eyes, but on mathematics and statistics. But before continuing, try applying some of this tools to your own project data.</p>
</div>
<div id="exercises-1" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Exercises<a href="bivariate-data-analysis.html#exercises-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now you will have some time to analyse your own project data. You can use any of the functions we learnt here by simply copying and pasting them in a new R file. You can start by askig the following questions:</p>
<ol style="list-style-type: decimal">
<li>How many numeric variables are in my data?</li>
<li>Can any of them be related?</li>
<li>Create a scatter plot two variables you suspect could be related. If you can, add marginal densities.</li>
<li>Do these variables need any type of transformation? Or do they not?</li>
<li>Are there any outliers? Create a bivariate box plot to find out</li>
<li>Is there any evidence of relationship between the two variables?</li>
<li>Create a new scatter plot, but now using the ggplot functions</li>
<li>Try to add a 3rd variable to your plot by modifying the color or the shape</li>
<li>Create a density plot</li>
</ol>
</div>
<div id="covariance" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Covariance<a href="bivariate-data-analysis.html#covariance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We previously learnt that, when analysing only one variable, we can calculate the standard deviation. The standard deviation is the “average distance” of observations to the mean. For example, in the following plots the average length of the dotted lines is the standard deviation. We can calculate the standard deviation for both population size and number of murders.</p>
<p>But since we have two variables, now we can ask a new question: are they related? do they change in the same way? If one goes up, does the other one also go up?</p>
<p>This question has a very simple meaning if we look at the plots below: it means, do both variables (population and murders) move “away” from the vertical line in the same direction? If gun murders moves to the right, does population also move to the right?</p>
<p><img src="_main_files/figure-html/unnamed-chunk-172-1.png" width="672" /></p>
<p>To answer this question, we can simply calculate the length of those dotted lines for each variable, then multiply it. Finally, we find the average. The idea is the following:</p>
<p>If both variables “move to the left” from the mean line, then both numbers will be negative and (-)<em>(-) = +
If both variables “move to the right”, then both numbers will be positive and (+)</em>(+) = +
If both variables “move in opposite directions:, then one will be positive and one negative, so (+)*(-) = -</p>
<p>This means that:</p>
<ol style="list-style-type: decimal">
<li>If we get a positive number, the variables are related. When one increases the other one increses too. We say that the variables “covariate”.</li>
<li>If we get a negative number, the variables are also related, but inversely. When one increases the other one increses too. The variables also “covariate”.</li>
<li>If we get zero, the variables are not related.</li>
</ol>
<p>We call this number covariance. The easiest way to calculate it in R is using the “cov()” function:</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="bivariate-data-analysis.html#cb288-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(dat<span class="sc">$</span>population, dat<span class="sc">$</span>total)</span></code></pre></div>
<pre><code>## [1] 0.2613055</code></pre>
<p>The number is positive, so number of murders and population size do covariate.</p>
<p>Note, however, that because the covariance is a multiplication it will depend on how big your numbers are. This means it is sensitive to units: if we work with centimeters, kilometeres or meters, we will get three different numbers. Because of this, the actual value of the correlation does not tell us anything at all: the only thing we can inerpret is the sign.</p>
</div>
<div id="correlation" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Correlation<a href="bivariate-data-analysis.html#correlation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It is dull that covariance will change depending on the units we use. After all, it should not matter in which units we measured our data!</p>
<p>To solve this problem, instead of calculating the covariance you can calculate the correlation. Correlations are “dimentionless” (they have no units) and they are designed so that, regardless of the units your data is in, you always get the same number. Correlations are calculated in R very easily using the function “cor()”.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="bivariate-data-analysis.html#cb290-1" aria-hidden="true" tabindex="-1"></a>corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(dat<span class="sc">$</span>population, dat<span class="sc">$</span>total)</span>
<span id="cb290-2"><a href="bivariate-data-analysis.html#cb290-2" aria-hidden="true" tabindex="-1"></a>corr</span></code></pre></div>
<pre><code>## [1] 0.8917199</code></pre>
<p>Correlations always go from -1 to 1, and the number is very intuitive to interpret:</p>
<ol style="list-style-type: decimal">
<li>If correlation is 1, the two variables have a perfect correlation: they form a line when plotted together</li>
<li>If correlation is -1, the two variables have a perfect inverse correlation: they form a line with negative slope</li>
<li>If correlation is 0, the variables are not related at all</li>
</ol>
<p>Anything in between are intermediate correlations, and the closer the number is to 1 (or -1) the stronger the relationship between variables is. For example, our data has a correlation of 0.89, which is very high. This tells us that population size and number of murders are quite related to each other: when one increases, the other one increases too.</p>
<p>If possible, you should always add the corresponding correlation value to any scatter plot you create. This adds information on how strong the relation between the variables actually is not only to our eyes, but statistically. Let’s add this number to our previous plot.</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="bivariate-data-analysis.html#cb292-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb292-2"><a href="bivariate-data-analysis.html#cb292-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>region)) <span class="sc">+</span> </span>
<span id="cb292-3"><a href="bivariate-data-analysis.html#cb292-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb292-4"><a href="bivariate-data-analysis.html#cb292-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>) <span class="sc">+</span></span>
<span id="cb292-5"><a href="bivariate-data-analysis.html#cb292-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb292-6"><a href="bivariate-data-analysis.html#cb292-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label=</span>abb)) <span class="sc">+</span> </span>
<span id="cb292-7"><a href="bivariate-data-analysis.html#cb292-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Gun murders in 2010. Cor = 8.892&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-175-1.png" width="672" /></p>
</div>
<div id="predictions-and-linear-models" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> Predictions and linear models<a href="bivariate-data-analysis.html#predictions-and-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s now look at the final and most interesting question: can we predict the average number of fun murders that will occur in a state if we know its population size? In statistics this type of problem is called “prediction”. Note, however, that we do not always want to “predict the future”. In this case, for instane, we want to know the value for a state with X number of inhabitants, but that state could’ve existed in the past, could exist in the present or could not even exist. So we will predicting does not always mean finding out things before they happen. In fact, a researchers spend a long time trying to predict past events in order to understand them better and find out what caused them.</p>
<p>The variable we want to predict is our dependent variable (in this case number of murders) and the variables we basing our prediciton on are the independent variables or predictors (in this case the population size). Note that we are right now dealing with the simplest type of prediction: we only have one variable. More often, scientists use tens or hundreds of variables to predict. To do this they implement machine learning techniques. We will look at this in future sessions.</p>
<p>The simplest type of predictive model is the “linear model”. A linear model assumes that you can represent the relationship between your two variables with a straight line (it has to be straight!). For example, like this:</p>
<p><img src="_main_files/figure-html/unnamed-chunk-176-1.png" width="672" /></p>
<p>If our states came from an ideal world, they would all fall on top of the line, but since they come from a “real world” full of noise and random variation, they scatter around the line, surrounding it.</p>
<p>The problem is, we do not know what this line looks like. Where does it start? Where does it end? How steep is it? It could be any of the following three lines, or any other line as a matter o fact:</p>
<p><img src="_main_files/figure-html/unnamed-chunk-177-1.png" width="672" /></p>
<p>There are an infinite number of possibilities! How to find the appropriate one?</p>
<p>As you will learn in the theoretical session accompanying this tutorial, the way find the ideal line (which we call the “best fit”) is by calculating the distance from every point to an imaginary line (we can change this imaginary line at our will) and adding up all these distances into a total number called the “Sum of squared residuals”. This name comes from the term “residual”, which is the statistical way of saying “distance from the point to the line” and from the fact that we square these numbers to eliminate all negative numbers. Then we find the line that minimises this number: the line that makes it as small as possible. What this means is we will find the line to which all points are closest to. We do this by applying differential calculus, which can be used to find “minimums” of functions.</p>
<p>This might sound overly complicated, but it is ridiculously easy to do it in R. All you need to do is run the function lm() (“lm” stands for linear model) and tell R where your data is stored. You will also need to add a formula with the following format:</p>
<p>what_i_want_to_predict ~ what_i_will_use_as_predictors</p>
<p>The ~ sign is read by R as “as a function of” or “depending on”.</p>
<p>Let’s do this and store the results in a variable called “res.lm”. It should only take a second to run. (Yes, R is finding the best line our of an infinite number of possibilities in under a second!).</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="bivariate-data-analysis.html#cb293-1" aria-hidden="true" tabindex="-1"></a>res.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> total <span class="sc">~</span> population, <span class="at">data =</span> dat)</span></code></pre></div>
<p>Now let’s have a look at our results:</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="bivariate-data-analysis.html#cb294-1" aria-hidden="true" tabindex="-1"></a>res.lm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = total ~ population, data = dat)
## 
## Coefficients:
## (Intercept)   population  
##      -6.439        1.271</code></pre>
<p>Simple and easy to read: R is telling us that our line is defined by the two numbers -6.439 and 1.271. Hence, the function of our line (the name of our line, if you will) is as follows:</p>
<p>logmurders = -6.439 + 1.271*logpopulation</p>
<p>You can access these two coefficients using the dollar operator ($) followed by “coefficients”:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="bivariate-data-analysis.html#cb296-1" aria-hidden="true" tabindex="-1"></a>res.lm<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)  population 
##   -6.439205    1.270876</code></pre>
<p>Let’s plot this “best fit” line and our points together:</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="bivariate-data-analysis.html#cb298-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb298-2"><a href="bivariate-data-analysis.html#cb298-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>region)) <span class="sc">+</span> </span>
<span id="cb298-3"><a href="bivariate-data-analysis.html#cb298-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;log10(Population size)&quot;</span>) <span class="sc">+</span></span>
<span id="cb298-4"><a href="bivariate-data-analysis.html#cb298-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;log10(Number of murders)&quot;</span>) <span class="sc">+</span></span>
<span id="cb298-5"><a href="bivariate-data-analysis.html#cb298-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb298-6"><a href="bivariate-data-analysis.html#cb298-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label=</span>abb)) <span class="sc">+</span> </span>
<span id="cb298-7"><a href="bivariate-data-analysis.html#cb298-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Gun murders in 2010. Cor = 0.892&quot;</span>) <span class="sc">+</span> </span>
<span id="cb298-8"><a href="bivariate-data-analysis.html#cb298-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span>res.lm<span class="sc">$</span>coefficients[<span class="dv">1</span>], <span class="at">slope=</span>res.lm<span class="sc">$</span>coefficients[<span class="dv">2</span>],  <span class="at">linetype=</span><span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-181-1.png" width="672" /></p>
<p>If we want to know more details about the linear model, we can use summary to display the key aspects of our results.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="bivariate-data-analysis.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res.lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = total ~ population, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.55966 -0.15092  0.00002  0.14696  1.09431 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -6.43920    0.60638  -10.62 2.64e-14 ***
## population   1.27088    0.09215   13.79  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2955 on 49 degrees of freedom
## Multiple R-squared:  0.7952, Adjusted R-squared:  0.791 
## F-statistic: 190.2 on 1 and 49 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Have a close look at the column named Pr(&gt;|t|). This column tells us if we have enough evidence to conclude that the prediction is valid or not. The smallest this number, the better!</p>
<p>Finally, let’s try to predict the number of murders in some hypothetical state with 50 million inhabitants (a really big state indeed!). Don’t forget that we applied a logarithm, so we will need ot include this in the prediction.</p>
<p>Let’s take the logarithm of 50 million:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="bivariate-data-analysis.html#cb301-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log10</span>(<span class="dv">50000000</span>)</span></code></pre></div>
<pre><code>## [1] 7.69897</code></pre>
<p>Now let’s feed this number to our “ideal line” equation:</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="bivariate-data-analysis.html#cb303-1" aria-hidden="true" tabindex="-1"></a>res.lm<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> res.lm<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">*</span><span class="fl">7.69897</span></span></code></pre></div>
<pre><code>## (Intercept) 
##    3.345233</code></pre>
<p>Now let’s take the “inverse logarithm” of these number, which basically means elevating 10 to that power:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="bivariate-data-analysis.html#cb305-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span><span class="sc">^</span><span class="fl">3.345233</span> </span></code></pre></div>
<pre><code>## [1] 2214.282</code></pre>
<p>We predict that a state of that size would have approximately 2214 registered murders by gun.</p>
<p>However, predictions are only estiamtes, and estimates are random. If we repeated the experiment hundreds of times, we would get multiple different results! Thus, we should always accompany a prediction with its confidence interval.</p>
<p>We can use ggplot to plot not only the regression line, but also the cofidence interval (shown as a shade). To do this, we use geom_smooth() and specify that we want a linear model (“lm”).</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="bivariate-data-analysis.html#cb307-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>population, <span class="at">y=</span>total)) <span class="sc">+</span> </span>
<span id="cb307-2"><a href="bivariate-data-analysis.html#cb307-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>region)) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb307-3"><a href="bivariate-data-analysis.html#cb307-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label=</span>abb)) <span class="sc">+</span> </span>
<span id="cb307-4"><a href="bivariate-data-analysis.html#cb307-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Gun murders in 2010. Cor = 0.892&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-186-1.png" width="672" /></p>
</div>
<div id="correlation-does-not-equal-causation" class="section level2 hasAnchor" number="3.8">
<h2><span class="header-section-number">3.8</span> Correlation does not equal causation<a href="bivariate-data-analysis.html#correlation-does-not-equal-causation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Finally, let’s look at a very illustrative example: the “divorce_margarine” data set. This data set contains data on divorce rates in Maine and per capita consumption of margarine in the US. Let’s store the data in the variable “div”.</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="bivariate-data-analysis.html#cb309-1" aria-hidden="true" tabindex="-1"></a>div <span class="ot">&lt;-</span> divorce_margarine</span></code></pre></div>
<p>Now let’s look at the first few lines:</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="bivariate-data-analysis.html#cb310-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(div)</span></code></pre></div>
<pre><code>##   divorce_rate_maine margarine_consumption_per_capita year
## 1                5.0                              8.2 2000
## 2                4.7                              7.0 2001
## 3                4.6                              6.5 2002
## 4                4.4                              5.3 2003
## 5                4.3                              5.2 2004
## 6                4.1                              4.0 2005</code></pre>
<p>Finally, let’s plot it and perform a linear model:</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="bivariate-data-analysis.html#cb312-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>div, <span class="fu">aes</span>(<span class="at">x=</span>margarine_consumption_per_capita, divorce_rate_maine)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Margarine consumption per capita&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Divorce rate in Maine&quot;</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-189-1.png" width="672" /></p>
<p>The relationship seems very high! Let’s calculate the correlation:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="bivariate-data-analysis.html#cb314-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(div<span class="sc">$</span>divorce_rate_maine, div<span class="sc">$</span>margarine_consumption_per_capita)</span></code></pre></div>
<pre><code>## [1] 0.9925585</code></pre>
<p>Indeed, the correlation is 0.93. An extermely high number!</p>
<p>Based on this, would we conclude that an increase in margarine consumption causes divorce? Of course not, this doesn’t make sense! This illustrates one of the most important problems in statistics, and one of the most common soures of error. We can NEVER conclude what is the cause of what using statistics. The only thing we can say is that the variables are related, but there might be thousands of explanations for why that is. For example, maybe states which consume more margarine have a life style where divorce is more common. None of them is the cause of the other: they are both a reflection of life style. Or maybe there is no relationship at all between margarine and divorce and this is just an odd coincidence! We really cannot know. The only way to determine what is the cause of a phenomenon is making well experiments (for example, recruiting couples and feeding them margarine or some other control food, then finding if those fed with margarine divorced more often). And even then it is difficult to control for unkown factors.</p>
<p>So the final message is the follwing: if two variables are correlated we know they might influence one another or reflect a commmon phenomenon, but we can not conclude any causality.</p>
</div>
<div id="exercises-2" class="section level2 hasAnchor" number="3.9">
<h2><span class="header-section-number">3.9</span> Exercises<a href="bivariate-data-analysis.html#exercises-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now you will have some time to analyse your own project data. You can use any of the functions we learnt here by simply copying and pasting them in a new R file. You can start by askig the following questions:</p>
<ol style="list-style-type: decimal">
<li>Take the two variables you worked with in the previous exercise. Calculate their covariance</li>
<li>Now calculate their correlation</li>
<li>Do they seem to follow a linear trend? If so, try to fit a linear model to them using the lm() function.</li>
<li>Now plot the “best fit” line. Does it approximate the data well enough?</li>
<li>If so, try to predict what some unobserved values would look like.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="univariate-data-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multivariate-data-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-Bivariate-data-analysis.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
