<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Machine Learning Fundamentals: Predicting Variables Using Neural Networks | Fundamentals of Data Analysis in R</title>
  <meta name="description" content="<p>This is a collection of tutorials that illustrate how to analyse data in R.
The topics touched on this collection span univariate data analysis, multivariate data analysis, and fundamentals of machine learning.</p>" />
  <meta name="generator" content="bookdown 0.28.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Machine Learning Fundamentals: Predicting Variables Using Neural Networks | Fundamentals of Data Analysis in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a collection of tutorials that illustrate how to analyse data in R.
The topics touched on this collection span univariate data analysis, multivariate data analysis, and fundamentals of machine learning.</p>" />
  <meta name="github-repo" content="eddiecg/Data-analysis-in-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Machine Learning Fundamentals: Predicting Variables Using Neural Networks | Fundamentals of Data Analysis in R" />
  
  <meta name="twitter:description" content="<p>This is a collection of tutorials that illustrate how to analyse data in R.
The topics touched on this collection span univariate data analysis, multivariate data analysis, and fundamentals of machine learning.</p>" />
  

<meta name="author" content="Eddie Cano-Gamez" />


<meta name="date" content="2022-08-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Fundamentals of Data Analysis in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to Programming in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#calculations-in-r"><i class="fa fa-check"></i><b>1.1</b> Calculations in R</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#variable-assignation-in-r"><i class="fa fa-check"></i><b>1.2</b> Variable assignation in R</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#data-types-in-r"><i class="fa fa-check"></i><b>1.3</b> Data types in R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#numeric-variables"><i class="fa fa-check"></i><b>1.3.1</b> Numeric variables</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#character-variables"><i class="fa fa-check"></i><b>1.3.2</b> Character variables</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#logical-variables"><i class="fa fa-check"></i><b>1.3.3</b> Logical variables</a></li>
<li class="chapter" data-level="1.3.4" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#categorical-variables-factors"><i class="fa fa-check"></i><b>1.3.4</b> Categorical variables (factors)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#working-with-multiple-numbers-in-r"><i class="fa fa-check"></i><b>1.4</b> Working with multiple numbers in R</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#vectors"><i class="fa fa-check"></i><b>1.4.1</b> Vectors</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#lists"><i class="fa fa-check"></i><b>1.4.2</b> Lists</a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#matrices"><i class="fa fa-check"></i><b>1.4.3</b> Matrices</a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#data-frames"><i class="fa fa-check"></i><b>1.4.4</b> Data frames</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#manipulating-data-in-r"><i class="fa fa-check"></i><b>1.5</b> Manipulating data in R</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#working-with-lists-of-data-frames"><i class="fa fa-check"></i><b>1.5.1</b> Working with lists of data frames</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#extending-rs-funcitonality-with-libraries"><i class="fa fa-check"></i><b>1.6</b> Extending R’s funcitonality with libraries</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#writing-data-from-r"><i class="fa fa-check"></i><b>1.7</b> Writing data from R</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#writing-human-readable-files"><i class="fa fa-check"></i><b>1.7.1</b> Writing human readable files</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#writing-binary-files"><i class="fa fa-check"></i><b>1.7.2</b> Writing binary files</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#reading-data-into-r"><i class="fa fa-check"></i><b>1.8</b> Reading data into R</a></li>
<li class="chapter" data-level="1.9" data-path="introduction-to-programming-in-r.html"><a href="introduction-to-programming-in-r.html#project-work"><i class="fa fa-check"></i><b>1.9</b> Project work</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html"><i class="fa fa-check"></i><b>2</b> Univariate Data Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#visualising-univariate-data"><i class="fa fa-check"></i><b>2.1</b> Visualising univariate data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#dot-plot-strip-chart"><i class="fa fa-check"></i><b>2.1.1</b> Dot plot / Strip chart</a></li>
<li class="chapter" data-level="2.1.2" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#histograms"><i class="fa fa-check"></i><b>2.1.2</b> Histograms</a></li>
<li class="chapter" data-level="2.1.3" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#density-plot"><i class="fa fa-check"></i><b>2.1.3</b> Density plot</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#summarising-univariate-data"><i class="fa fa-check"></i><b>2.2</b> Summarising univariate data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#mean"><i class="fa fa-check"></i><b>2.2.1</b> Mean</a></li>
<li class="chapter" data-level="2.2.2" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#median"><i class="fa fa-check"></i><b>2.2.2</b> Median</a></li>
<li class="chapter" data-level="2.2.3" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#quantiles"><i class="fa fa-check"></i><b>2.2.3</b> Quantiles</a></li>
<li class="chapter" data-level="2.2.4" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#standard-deviation"><i class="fa fa-check"></i><b>2.2.4</b> Standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#comparing-data-to-probability-distributions"><i class="fa fa-check"></i><b>2.3</b> Comparing data to probability distributions</a></li>
<li class="chapter" data-level="2.4" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#box-plots"><i class="fa fa-check"></i><b>2.4</b> Box plots</a></li>
<li class="chapter" data-level="2.5" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#data-as-a-random-sample"><i class="fa fa-check"></i><b>2.5</b> Data as a random sample</a></li>
<li class="chapter" data-level="2.6" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
<li class="chapter" data-level="2.7" data-path="univariate-data-analysis.html"><a href="univariate-data-analysis.html#references"><i class="fa fa-check"></i><b>2.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html"><i class="fa fa-check"></i><b>3</b> Bivariate Data Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#visualising-two-variables"><i class="fa fa-check"></i><b>3.1</b> Visualising two variables</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#scatter-plot"><i class="fa fa-check"></i><b>3.1.1</b> Scatter plot</a></li>
<li class="chapter" data-level="3.1.2" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#bivariate-box-plots"><i class="fa fa-check"></i><b>3.1.2</b> Bivariate box plots</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#applying-transformations-to-a-variable"><i class="fa fa-check"></i><b>3.2</b> Applying transformations to a variable</a></li>
<li class="chapter" data-level="3.3" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#using-ggplot2-to-create-personalised-plots"><i class="fa fa-check"></i><b>3.3</b> Using ggplot2 to create personalised plots</a></li>
<li class="chapter" data-level="3.4" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#exercises-1"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
<li class="chapter" data-level="3.5" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#covariance"><i class="fa fa-check"></i><b>3.5</b> Covariance</a></li>
<li class="chapter" data-level="3.6" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#correlation"><i class="fa fa-check"></i><b>3.6</b> Correlation</a></li>
<li class="chapter" data-level="3.7" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#predictions-and-linear-models"><i class="fa fa-check"></i><b>3.7</b> Predictions and linear models</a></li>
<li class="chapter" data-level="3.8" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#correlation-does-not-equal-causation"><i class="fa fa-check"></i><b>3.8</b> Correlation does not equal causation</a></li>
<li class="chapter" data-level="3.9" data-path="bivariate-data-analysis.html"><a href="bivariate-data-analysis.html#exercises-2"><i class="fa fa-check"></i><b>3.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html"><i class="fa fa-check"></i><b>4</b> Multivariate Data Analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#exploring-one-variable-at-a-time"><i class="fa fa-check"></i><b>4.1</b> Exploring one variable at a time</a></li>
<li class="chapter" data-level="4.2" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#analysing-all-variables-jointly"><i class="fa fa-check"></i><b>4.2</b> Analysing all variables jointly</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#scatter-plot-matrices"><i class="fa fa-check"></i><b>4.2.1</b> Scatter plot matrices</a></li>
<li class="chapter" data-level="4.2.2" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#correlation-plots"><i class="fa fa-check"></i><b>4.2.2</b> Correlation plots</a></li>
<li class="chapter" data-level="4.2.3" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#the-distance-matrix"><i class="fa fa-check"></i><b>4.2.3</b> The distance matrix</a></li>
<li class="chapter" data-level="4.2.4" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#clustering-and-dendrograms"><i class="fa fa-check"></i><b>4.2.4</b> Clustering and dendrograms</a></li>
<li class="chapter" data-level="4.2.5" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#heatmaps"><i class="fa fa-check"></i><b>4.2.5</b> Heatmaps</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#exercises-3"><i class="fa fa-check"></i><b>4.3</b> Exercises</a></li>
<li class="chapter" data-level="4.4" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#reducing-the-number-of-dimensions"><i class="fa fa-check"></i><b>4.4</b> Reducing the number of dimensions</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#combining-dimensionality-reduction-with-clustering"><i class="fa fa-check"></i><b>4.4.1</b> Combining dimensionality reduction with clustering</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#exercises-4"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
<li class="chapter" data-level="4.6" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#references-1"><i class="fa fa-check"></i><b>4.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html"><i class="fa fa-check"></i><b>5</b> Web scraping in R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#example-scraping-the-imdb-website"><i class="fa fa-check"></i><b>5.1</b> Example: Scraping the IMDB website</a></li>
<li class="chapter" data-level="5.2" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#extracting-variables-using-css-selectors"><i class="fa fa-check"></i><b>5.2</b> Extracting variables using CSS selectors</a></li>
<li class="chapter" data-level="5.3" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#scraping-multiple-fields-from-a-website"><i class="fa fa-check"></i><b>5.3</b> Scraping multiple fields from a website</a></li>
<li class="chapter" data-level="5.4" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#performing-exploratory-data-analysis-eda-on-scraped-data"><i class="fa fa-check"></i><b>5.4</b> Performing exploratory data analysis (EDA) on scraped data</a></li>
<li class="chapter" data-level="5.5" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#exercises-5"><i class="fa fa-check"></i><b>5.5</b> Exercises</a></li>
<li class="chapter" data-level="5.6" data-path="web-scraping-in-r.html"><a href="web-scraping-in-r.html#references-2"><i class="fa fa-check"></i><b>5.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><i class="fa fa-check"></i><b>6</b> Machine Learning Fundamentals: Spam Detection Using a Naive Bayes Classifier</a>
<ul>
<li class="chapter" data-level="6.1" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#visualising-data"><i class="fa fa-check"></i><b>6.1</b> Visualising data</a></li>
<li class="chapter" data-level="6.2" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#pre-processing-data"><i class="fa fa-check"></i><b>6.2</b> Pre-processing data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#converting-data-to-corpus"><i class="fa fa-check"></i><b>6.2.1</b> Converting data to corpus</a></li>
<li class="chapter" data-level="6.2.2" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#cleaning-data"><i class="fa fa-check"></i><b>6.2.2</b> Cleaning data</a></li>
<li class="chapter" data-level="6.2.3" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#visualising-clean-data"><i class="fa fa-check"></i><b>6.2.3</b> Visualising clean data</a></li>
<li class="chapter" data-level="6.2.4" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#tokenising"><i class="fa fa-check"></i><b>6.2.4</b> Tokenising</a></li>
<li class="chapter" data-level="6.2.5" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#dividing-data-into-training-and-testing-set"><i class="fa fa-check"></i><b>6.2.5</b> Dividing data into training and testing set</a></li>
<li class="chapter" data-level="6.2.6" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#correcting-data-sparsity"><i class="fa fa-check"></i><b>6.2.6</b> Correcting data sparsity</a></li>
<li class="chapter" data-level="6.2.7" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#converting-data-to-word-appearance-table"><i class="fa fa-check"></i><b>6.2.7</b> Converting data to word appearance table</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#predicting-spam-and-non-spam"><i class="fa fa-check"></i><b>6.3</b> Predicting spam and non-spam</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#training-classifier"><i class="fa fa-check"></i><b>6.3.1</b> Training classifier</a></li>
<li class="chapter" data-level="6.3.2" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#testing-classifier"><i class="fa fa-check"></i><b>6.3.2</b> Testing classifier</a></li>
<li class="chapter" data-level="6.3.3" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#evaluating-performance"><i class="fa fa-check"></i><b>6.3.3</b> Evaluating performance</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#discussion"><i class="fa fa-check"></i><b>6.4</b> Discussion</a></li>
<li class="chapter" data-level="6.5" data-path="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html"><a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html#references-3"><i class="fa fa-check"></i><b>6.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><i class="fa fa-check"></i><b>7</b> Machine Learning Fundamentals: Predicting Variables Using Neural Networks</a>
<ul>
<li class="chapter" data-level="7.1" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#normalising-data"><i class="fa fa-check"></i><b>7.1</b> Normalising data</a></li>
<li class="chapter" data-level="7.2" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#visualising-data-1"><i class="fa fa-check"></i><b>7.2</b> Visualising data</a></li>
<li class="chapter" data-level="7.3" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#creating-neural-network"><i class="fa fa-check"></i><b>7.3</b> Creating neural network</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#spliting-data-into-training-and-testing-sets"><i class="fa fa-check"></i><b>7.3.1</b> Spliting data into training and testing sets</a></li>
<li class="chapter" data-level="7.3.2" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#training-neural-network"><i class="fa fa-check"></i><b>7.3.2</b> Training neural network</a></li>
<li class="chapter" data-level="7.3.3" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#testing-neural-network"><i class="fa fa-check"></i><b>7.3.3</b> Testing neural network</a></li>
<li class="chapter" data-level="7.3.4" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#evaluating-performance-1"><i class="fa fa-check"></i><b>7.3.4</b> Evaluating performance</a></li>
<li class="chapter" data-level="7.3.5" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#improving-performance-by-adding-hidden-nodes"><i class="fa fa-check"></i><b>7.3.5</b> Improving performance by adding hidden nodes</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#conclusions"><i class="fa fa-check"></i><b>7.4</b> Conclusions</a></li>
<li class="chapter" data-level="7.5" data-path="machine-learning-fundamentals-predicting-variables-using-neural-networks.html"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#references-4"><i class="fa fa-check"></i><b>7.5</b> References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fundamentals of Data Analysis in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="machine-learning-fundamentals-predicting-variables-using-neural-networks" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Machine Learning Fundamentals: Predicting Variables Using Neural Networks<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#machine-learning-fundamentals-predicting-variables-using-neural-networks" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the previous sessions we learnt how to read and explore data with multiple variables/dimensions in R, as well as how to build a spam filter using machine learning (Naive Bayes). Finally, we will learn how to build a simple neural network using R.</p>
<p>Recall that neural networks are machine learning algorithms inspired by the biology of the brain and which can be used for the two following tasks:</p>
<ol style="list-style-type: upper-alpha">
<li><p>Prediction: Using a set of independent variables to “predict” a dependent variable (just as in linear regression, only with multiple variables).</p></li>
<li><p>Classification: Clasifying an individual observation into one of the possible groups of classes.</p></li>
</ol>
<p>In this session we will build a neural network to predict the strength of concrete. To do so, we will use data from 1030 different types of concrete, each with a different age and composition.</p>
<p>Before starting this session we need to install a new R libraries called “neuralnet.” To install this library, simply run the following line of code.</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb458-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;neuralnet&quot;</span>)</span></code></pre></div>
<p>Let’s now load the required libraries.</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb459-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(neuralnet)</span>
<span id="cb459-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb459-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pheatmap)</span>
<span id="cb459-3"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb459-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb459-4"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb459-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>You can find the data for this session in the “Data” directory, along with the other materials for this course. The file is called “concrete.csv”. Let’s read this into R.</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb460-1" aria-hidden="true" tabindex="-1"></a>concrete <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;./Data/concrete.csv&quot;</span>)</span></code></pre></div>
<p>We use the head function to look at the first 6 lines of the table.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb461-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(concrete)</span></code></pre></div>
<pre><code>##   cement  slag   ash water superplastic coarseagg fineagg age strength
## 1  141.3 212.0   0.0 203.5          0.0     971.8   748.5  28    29.89
## 2  168.9  42.2 124.3 158.3         10.8    1080.8   796.2  14    23.51
## 3  250.0   0.0  95.7 187.4          5.5     956.9   861.2  28    29.22
## 4  266.0 114.0   0.0 228.0          0.0     932.0   670.0  28    45.85
## 5  154.8 183.4   0.0 193.3          9.1    1047.4   696.7  28    18.29
## 6  255.0   0.0   0.0 192.0          0.0     889.8   945.0  90    21.86</code></pre>
<p>We can see that this data contains measurements on the following characteristics of concrete:</p>
<ol style="list-style-type: decimal">
<li>Amount of cement (kg/m3)</li>
<li>Amount of slag (kg/m3)</li>
<li>Amount of ash (kg/m3)</li>
<li>Amount of water (kg/m3)</li>
<li>Amount of superplasticizer (kg/m3)</li>
<li>Amount of coarse aggregate (kg/m3)</li>
<li>Amount of fine aggregate (kg/m3)</li>
<li>Aging time (days)</li>
<li>Compressive strength</li>
</ol>
<p>Let’s now use the dim() function to find out how many samples of concrete were measured:</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(concrete)</span></code></pre></div>
<pre><code>## [1] 1030    9</code></pre>
<p>Our data contains measurements on 1,030 different samples of concrete.</p>
<div id="normalising-data" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Normalising data<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#normalising-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before analysing the data, let’s use the summary() function to find out how each variable behaves.</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb465-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(concrete)</span></code></pre></div>
<pre><code>##      cement           slag            ash             water        superplastic      coarseagg         fineagg           age            strength    
##  Min.   :102.0   Min.   :  0.0   Min.   :  0.00   Min.   :121.8   Min.   : 0.000   Min.   : 801.0   Min.   :594.0   Min.   :  1.00   Min.   : 2.33  
##  1st Qu.:192.4   1st Qu.:  0.0   1st Qu.:  0.00   1st Qu.:164.9   1st Qu.: 0.000   1st Qu.: 932.0   1st Qu.:731.0   1st Qu.:  7.00   1st Qu.:23.71  
##  Median :272.9   Median : 22.0   Median :  0.00   Median :185.0   Median : 6.400   Median : 968.0   Median :779.5   Median : 28.00   Median :34.45  
##  Mean   :281.2   Mean   : 73.9   Mean   : 54.19   Mean   :181.6   Mean   : 6.205   Mean   : 972.9   Mean   :773.6   Mean   : 45.66   Mean   :35.82  
##  3rd Qu.:350.0   3rd Qu.:142.9   3rd Qu.:118.30   3rd Qu.:192.0   3rd Qu.:10.200   3rd Qu.:1029.4   3rd Qu.:824.0   3rd Qu.: 56.00   3rd Qu.:46.13  
##  Max.   :540.0   Max.   :359.4   Max.   :200.10   Max.   :247.0   Max.   :32.200   Max.   :1145.0   Max.   :992.6   Max.   :365.00   Max.   :82.60</code></pre>
<p>Note that while the amount of cement can go from 102 to 540 kg/m3, the amount of coarse aggregate can go from 801 to 1029 kg/m3. These ranges are very different to each other, so we cannot compare simply compare both measurements! Moreover, NEURAL NETWORKS ONLY WORK ON VALUES CLOSE TO ZERO. Because of these two reasons, let’s “rescale” the values of all columns, so that they go from 0 to 1 only. This process is called “rescaling” or “normalisation”.</p>
<p>We define a function called “normalisation”, which takes a series of numbers (x) and normalises it, so that the numbers go from 0 to 1 only. The function finally resturns all of these “new x” values.</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb467-1" aria-hidden="true" tabindex="-1"></a>normalise <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb467-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb467-2" aria-hidden="true" tabindex="-1"></a>  new.x <span class="ot">&lt;-</span> (x <span class="sc">-</span><span class="fu">min</span>(x))<span class="sc">/</span>(<span class="fu">max</span>(x)<span class="sc">-</span><span class="fu">min</span>(x))</span>
<span id="cb467-3"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb467-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Next, we apply this function to all the columns of our data. We do this using “apply”. We set the MARGIN to 2, because we want to apply the function to the columns. We store the new data in a variable called “concrete_norm” (norm for normalised).</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb468-1" aria-hidden="true" tabindex="-1"></a>concrete_norm <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">apply</span>(concrete, <span class="at">MARGIN=</span><span class="dv">2</span>, normalise))</span></code></pre></div>
<p>Let’s use head() to look at the first lines of the data.</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb469-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(concrete_norm)</span></code></pre></div>
<pre><code>##       cement      slag       ash     water superplastic coarseagg   fineagg        age  strength
## 1 0.08972603 0.5898720 0.0000000 0.6525559    0.0000000 0.4965116 0.3876066 0.07417582 0.3433412
## 2 0.15273973 0.1174179 0.6211894 0.2915335    0.3354037 0.8133721 0.5072755 0.03571429 0.2638595
## 3 0.33789954 0.0000000 0.4782609 0.5239617    0.1708075 0.4531977 0.6703462 0.07417582 0.3349944
## 4 0.37442922 0.3171953 0.0000000 0.8482428    0.0000000 0.3808140 0.1906673 0.07417582 0.5421702
## 5 0.12054795 0.5102949 0.0000000 0.5710863    0.2826087 0.7162791 0.2576518 0.07417582 0.1988290
## 6 0.34931507 0.0000000 0.0000000 0.5607029    0.0000000 0.2581395 0.8805820 0.24450549 0.2433038</code></pre>
<p>We see that now all values are between zero and one. To verify that this is the case, let’s use the summary function.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb471-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(concrete_norm)</span></code></pre></div>
<pre><code>##      cement            slag              ash             water         superplastic      coarseagg         fineagg            age             strength     
##  Min.   :0.0000   Min.   :0.00000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :0.0000  
##  1st Qu.:0.2063   1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.3442   1st Qu.:0.0000   1st Qu.:0.3808   1st Qu.:0.3436   1st Qu.:0.01648   1st Qu.:0.2664  
##  Median :0.3902   Median :0.06121   Median :0.0000   Median :0.5048   Median :0.1988   Median :0.4855   Median :0.4654   Median :0.07418   Median :0.4001  
##  Mean   :0.4091   Mean   :0.20561   Mean   :0.2708   Mean   :0.4774   Mean   :0.1927   Mean   :0.4998   Mean   :0.4505   Mean   :0.12270   Mean   :0.4172  
##  3rd Qu.:0.5662   3rd Qu.:0.39775   3rd Qu.:0.5912   3rd Qu.:0.5607   3rd Qu.:0.3168   3rd Qu.:0.6640   3rd Qu.:0.5770   3rd Qu.:0.15110   3rd Qu.:0.5457  
##  Max.   :1.0000   Max.   :1.00000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.00000   Max.   :1.0000</code></pre>
<p>Indeed, notice how the minimum and maximum values are 0 and 1 respectively for ALL columns in our table. Now we are ready to analyse the data.</p>
</div>
<div id="visualising-data-1" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Visualising data<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#visualising-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before building our neural network, let’s use the techniques we have learnt before to explore the concrete data. For example, let’s calculate the correlation matrix.</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb473-1" aria-hidden="true" tabindex="-1"></a>corrmat <span class="ot">&lt;-</span> <span class="fu">cor</span>(concrete_norm)</span></code></pre></div>
<p>Let’s use corrplot() to visualise the correlation matrix. We will ask R to plot the most similar variables together (recall that we can do this by setting order=“hclust”).</p>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb474-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(corrmat,</span>
<span id="cb474-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb474-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">type =</span> <span class="st">&quot;upper&quot;</span>,</span>
<span id="cb474-3"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb474-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;ellipse&quot;</span>,</span>
<span id="cb474-4"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb474-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">order =</span> <span class="st">&quot;hclust&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-282-1.png" width="672" /></p>
<p>We can already conclude some things from this graph. For example, the strength of concrete is highly correlated with the amount of cement we put in it. Thus, if we want to build stronger concrete we might need to add more cement. We can also see that the amount of superplasticizer is inversely proportional to the aging time. This might mean that as concrete ages, the plasticizer is degraded and disappears.</p>
<p>Let’s now use the data to build a heat map.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb475-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pheatmap</span>(concrete_norm, <span class="at">show_rownames =</span> F)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-283-1.png" width="672" /></p>
<p>From this graph we get even further information. For instance, notice how there are at least 6 different “types” of concrete (you can see this in the way rows have been ordered into a tree).</p>
<p>Finally, let’s try to reduce the dimensions of the data using PCA.</p>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb476-1" aria-hidden="true" tabindex="-1"></a>pcs <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(concrete_norm)</span></code></pre></div>
<p>A closer look at PC1 and PC2 tells us that one of the main differences between different concretes is the amount of ash. In fact, PC1 (our most important new axis) separates concretes into those with low ash content and those with high ash content.</p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb477-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(pcs<span class="sc">$</span>x), <span class="fu">aes</span>(PC1, PC2)) <span class="sc">+</span> </span>
<span id="cb477-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb477-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>concrete_norm<span class="sc">$</span>ash)) <span class="sc">+</span></span>
<span id="cb477-3"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb477-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_continuous</span>(<span class="at">name=</span><span class="st">&quot;Ash&quot;</span>) <span class="sc">+</span></span>
<span id="cb477-4"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb477-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-285-1.png" width="672" /></p>
<p>We have learnt a lot from the data already, but we still do not know how to predict its strength. If we know the composition of a concrete sample, can we predict how strong it will be and, thus, which things we should and should not build with it? Let’s build a neural network to answer this question.</p>
</div>
<div id="creating-neural-network" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Creating neural network<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#creating-neural-network" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Remember that machine learning is done in two steps: training and testing. Thus, let’s first divide the data into a training and a testing set.</p>
<div id="spliting-data-into-training-and-testing-sets" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Spliting data into training and testing sets<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#spliting-data-into-training-and-testing-sets" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will allocate 75% of our observations (773 in total) to the training data set and the remaining 25% (257) to the testing data set.</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb478-1" aria-hidden="true" tabindex="-1"></a>concrete_training <span class="ot">&lt;-</span> concrete_norm[<span class="dv">1</span><span class="sc">:</span><span class="dv">773</span>,]</span>
<span id="cb478-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb478-2" aria-hidden="true" tabindex="-1"></a>concrete_testing <span class="ot">&lt;-</span> concrete_norm[<span class="dv">773</span><span class="sc">:</span><span class="dv">1030</span>,]</span></code></pre></div>
</div>
<div id="training-neural-network" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Training neural network<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#training-neural-network" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now we are able to build and test the neural network. To do this, we will use the neuralnet() function, specifying which are the independent and which the dependent variables (into a formula). For now, let’s build the most simple possible network: one with just one hidden node!</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb479-1" aria-hidden="true" tabindex="-1"></a>my_NN <span class="ot">&lt;-</span> <span class="fu">neuralnet</span>(strength <span class="sc">~</span> cement <span class="sc">+</span> slag <span class="sc">+</span> ash <span class="sc">+</span> water <span class="sc">+</span> </span>
<span id="cb479-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb479-2" aria-hidden="true" tabindex="-1"></a>                     superplastic <span class="sc">+</span> coarseagg <span class="sc">+</span> fineagg <span class="sc">+</span> age,</span>
<span id="cb479-3"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb479-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> concrete_training,</span>
<span id="cb479-4"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb479-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">hidden =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Our network has been trained! Let’s have a look at its shape (its topology) using the plot function.</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb480-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(my_NN)</span></code></pre></div>
<p>Notice that it more than 1,000 iterations to build this network, despite it being so simple.</p>
</div>
<div id="testing-neural-network" class="section level3 hasAnchor" number="7.3.3">
<h3><span class="header-section-number">7.3.3</span> Testing neural network<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#testing-neural-network" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now we can test the performance of the network. We use the compute() function to try and predict the strength of concrete in the testing set.</p>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb481-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">compute</span>(my_NN, concrete_testing[,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>])</span></code></pre></div>
<p>Let’s use head() to look at the first 6 predictions done by our network.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb482-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(results<span class="sc">$</span>net.result)</span></code></pre></div>
<pre><code>##          [,1]
## 773 0.1937926
## 774 0.3271159
## 775 0.4669493
## 776 0.2376992
## 777 0.6725225
## 778 0.4643841</code></pre>
</div>
<div id="evaluating-performance-1" class="section level3 hasAnchor" number="7.3.4">
<h3><span class="header-section-number">7.3.4</span> Evaluating performance<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#evaluating-performance-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, let’s evaluate how well these predictions are by comparing them with the true concrete strength. This is possible because we knew the true values from the beginning! Let’s build a scatter plot of prediciton versus reality.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb484-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(concrete_testing<span class="sc">$</span>strength, results<span class="sc">$</span>net.result, </span>
<span id="cb484-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb484-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Artificial NN with 3 layers and 1 hidden node&quot;</span>,</span>
<span id="cb484-3"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb484-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;True concrete strength&quot;</span>,</span>
<span id="cb484-4"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb484-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Predicted concrete strength&quot;</span>)</span>
<span id="cb484-5"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb484-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(results<span class="sc">$</span>net.result <span class="sc">~</span> concrete_testing<span class="sc">$</span>strength))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-291-1.png" width="672" /></p>
<p>Notice how well the network perform, despite being so simple! In fact, if we calculate the correlation we’ll see that it is higher than 0.8</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb485-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(concrete_testing<span class="sc">$</span>strength, results<span class="sc">$</span>net.result)</span></code></pre></div>
<pre><code>##           [,1]
## [1,] 0.8069152</code></pre>
</div>
<div id="improving-performance-by-adding-hidden-nodes" class="section level3 hasAnchor" number="7.3.5">
<h3><span class="header-section-number">7.3.5</span> Improving performance by adding hidden nodes<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#improving-performance-by-adding-hidden-nodes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>However, these predictions are still not good enough. What if we wanted to evaluate which concrete is the best for a really important bridge? We cannot risk overestimating the strength and making a bridge collapse! Thus, let’s try to improve our predictions. To do this, we will recreate the network, but now making it much more complex. In fact, let’s add 6 hidden nodes to the middle layer.</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb487-1" aria-hidden="true" tabindex="-1"></a>my_NN <span class="ot">&lt;-</span> <span class="fu">neuralnet</span>(strength <span class="sc">~</span> cement <span class="sc">+</span> slag <span class="sc">+</span> ash <span class="sc">+</span> water <span class="sc">+</span> </span>
<span id="cb487-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb487-2" aria-hidden="true" tabindex="-1"></a>                     superplastic <span class="sc">+</span> coarseagg <span class="sc">+</span> fineagg <span class="sc">+</span> age,</span>
<span id="cb487-3"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb487-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> concrete_training,</span>
<span id="cb487-4"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb487-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">hidden =</span> <span class="dv">6</span>)</span></code></pre></div>
<p>The new topology of the network looks as follows:</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb488-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb488-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(my_NN)</span></code></pre></div>
<p>Note how it took more than 50,000 iterations to build this network configuration!!!</p>
<p>Let’s predict the concrete strengths again, using the new neural network.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb489-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">compute</span>(my_NN, concrete_testing[,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>])</span></code></pre></div>
<p>To evaluate the performance, let’s plot the predicted values versus the true values.</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb490-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(concrete_testing<span class="sc">$</span>strength, results<span class="sc">$</span>net.result, </span>
<span id="cb490-2"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb490-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Artificial NN with 3 layers and 6 hidden nodes&quot;</span>,</span>
<span id="cb490-3"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb490-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;True concrete strength&quot;</span>,</span>
<span id="cb490-4"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb490-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Predicted concrete strength&quot;</span>)</span>
<span id="cb490-5"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb490-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(results<span class="sc">$</span>net.result <span class="sc">~</span> concrete_testing<span class="sc">$</span>strength))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-296-1.png" width="672" /></p>
<p>The points fall in an almost perfect line! In fact, if we calculate the correlation we will notice that it has improved to more than 0.9.</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#cb491-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(concrete_testing<span class="sc">$</span>strength, results<span class="sc">$</span>net.result)</span></code></pre></div>
<pre><code>##           [,1]
## [1,] 0.9230662</code></pre>
<p>This means that our neural network correctly predicts the strength of concrete using these 8 variables. We can now be confident enough to use it in new data.</p>
</div>
</div>
<div id="conclusions" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Conclusions<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#conclusions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now you know how to build simple neural networks in R. You can apply this knowledge to predict or classify any data you might be interested in.</p>
</div>
<div id="references-4" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> References<a href="machine-learning-fundamentals-predicting-variables-using-neural-networks.html#references-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This turotial was adapted from:</p>
<ol style="list-style-type: decimal">
<li>Lantz B. (2013). Chapter 7. Neural Networks and Support Vector Machines in Machine Learning with R. Birmingham: Packt Publishing.</li>
</ol>
<p>Concrete strength data comes from the following study:</p>
<ol start="2" style="list-style-type: decimal">
<li>Yeh IC. (1998). Modelling of strength of high performance concrete using artificial neural networks. Cemenr and Concrete Research. Vol 28. pp 1797-1808.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="machine-learning-fundamentals-spam-detection-using-a-naive-bayes-classifier.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/07-Neural-networks-for-predicting-concrete-strength.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
